/**
 * 🚨 AUTO-GENERATED FILE — DO NOT EDIT MANUALLY
 *
 * Generated by scripts/train-agents.ts on 2025-10-05T02:02:40.317Z
 */

export const trainedAgents = {
  "generatedAt": "2025-10-05T02:02:40.317Z",
  "models": {
    "custodian": {
      "name": "llama3.1-distilled",
      "baseModel": "llama3.1",
      "size": "7B",
      "loraConfig": {
        "rank": 8,
        "alpha": 16,
        "dropout": 0.05,
        "targetModules": [
          "q_proj",
          "v_proj"
        ]
      },
      "quantization": "4bit",
      "maxMemoryMB": 600,
      "loadTimeMs": 30
    },
    "diplomat": {
      "name": "llama3.1-distilled",
      "baseModel": "llama3.1",
      "size": "7B",
      "loraConfig": {
        "rank": 8,
        "alpha": 16,
        "dropout": 0.05,
        "targetModules": [
          "q_proj",
          "v_proj"
        ]
      },
      "quantization": "4bit",
      "maxMemoryMB": 600,
      "loadTimeMs": 30
    },
    "narrator": {
      "name": "llama3.1-distilled",
      "baseModel": "llama3.1",
      "size": "7B",
      "loraConfig": {
        "rank": 8,
        "alpha": 16,
        "dropout": 0.05,
        "targetModules": [
          "q_proj",
          "v_proj"
        ]
      },
      "quantization": "4bit",
      "maxMemoryMB": 600,
      "loadTimeMs": 30
    },
    "explorer": {
      "name": "llama3.1-distilled",
      "baseModel": "llama3.1",
      "size": "7B",
      "loraConfig": {
        "rank": 8,
        "alpha": 16,
        "dropout": 0.05,
        "targetModules": [
          "q_proj",
          "v_proj"
        ]
      },
      "quantization": "4bit",
      "maxMemoryMB": 600,
      "loadTimeMs": 30
    },
    "storyteller": {
      "name": "llama3.1-distilled",
      "baseModel": "llama3.1",
      "size": "7B",
      "loraConfig": {
        "rank": 8,
        "alpha": 16,
        "dropout": 0.05,
        "targetModules": [
          "q_proj",
          "v_proj"
        ]
      },
      "quantization": "4bit",
      "maxMemoryMB": 600,
      "loadTimeMs": 30
    }
  },
  "datasets": {
    "custodian": {
      "size": 400,
      "templates": [
        "banking",
        "social",
        "game",
        "physics",
        "workflow"
      ],
      "violationTypes": [
        "overdraft",
        "duplicate_username",
        "entropy_spike",
        "invalid_transfer"
      ]
    },
    "diplomat": {
      "size": 200,
      "templates": [
        "banking",
        "social",
        "game",
        "physics",
        "workflow"
      ]
    },
    "narrator": {
      "size": 300,
      "modes": [
        "kid",
        "pm",
        "engineer"
      ]
    },
    "explorer": {
      "size": 150,
      "paradoxTypes": [
        "quantum",
        "temporal",
        "logical",
        "causal"
      ]
    },
    "storyteller": {
      "size": 300,
      "domains": [
        "banking",
        "social",
        "game",
        "physics",
        "workflow"
      ]
    }
  },
  "knowledge": {
    "custodian": {
      "overdraft": {
        "law": "balance >= 0",
        "severity": "high",
        "recommendedProposal": {
          "id": "proposal-0",
          "type": "rollback",
          "steps": [
            {
              "action": "revert_transaction",
              "target": "account:72",
              "params": {
                "amount": 100
              },
              "preconditions": [
                "transaction.exists"
              ],
              "postconditions": [
                "balance >= 0"
              ]
            }
          ],
          "proof": "Proof: balance >= 0 violated. Rollback restores invariant.",
          "confidence": 0.9448466387270635,
          "estimatedCost": 30
        },
        "reasoning": "Detected overdraft on account:72. Proposing patch to restore law: balance >= 0"
      },
      "duplicate_username": {
        "law": "username.unique === true",
        "severity": "medium",
        "recommendedProposal": {
          "id": "proposal-1",
          "type": "rollback",
          "steps": [
            {
              "action": "revert_transaction",
              "target": "user:854",
              "params": {
                "amount": 100
              },
              "preconditions": [
                "transaction.exists"
              ],
              "postconditions": [
                "balance >= 0"
              ]
            }
          ],
          "proof": "Proof: username.unique === true violated. Rollback restores invariant.",
          "confidence": 0.9623710729184782,
          "estimatedCost": 94
        },
        "reasoning": "Detected duplicate_username on user:854. Proposing rollback to restore law: username.unique === true"
      },
      "entropy_spike": {
        "law": "entropy.delta >= 0",
        "severity": "critical",
        "recommendedProposal": {
          "id": "proposal-8",
          "type": "rollback",
          "steps": [
            {
              "action": "revert_transaction",
              "target": "system:39",
              "params": {
                "amount": 100
              },
              "preconditions": [
                "transaction.exists"
              ],
              "postconditions": [
                "balance >= 0"
              ]
            }
          ],
          "proof": "Proof: entropy.delta >= 0 violated. Rollback restores invariant.",
          "confidence": 0.8859593915882624,
          "estimatedCost": 73
        },
        "reasoning": "Detected entropy_spike on system:39. Proposing patch to restore law: entropy.delta >= 0"
      },
      "invalid_transfer": {
        "law": "sum(transactions.amount) === balance",
        "severity": "medium",
        "recommendedProposal": {
          "id": "proposal-10",
          "type": "patch",
          "steps": [
            {
              "action": "revert_transaction",
              "target": "transaction:9907",
              "params": {
                "amount": 100
              },
              "preconditions": [
                "transaction.exists"
              ],
              "postconditions": [
                "balance >= 0"
              ]
            }
          ],
          "proof": "Proof: sum(transactions.amount) === balance violated. Rollback restores invariant.",
          "confidence": 0.9468308036461959,
          "estimatedCost": 97
        },
        "reasoning": "Detected invalid_transfer on transaction:9907. Proposing patch to restore law: sum(transactions.amount) === balance"
      }
    },
    "diplomat": {
      "banking::social": {
        "mergeStrategy": "federation",
        "agreements": [
          {
            "type": "shared_law",
            "description": "Both universes maintain data integrity",
            "implementation": [
              "validate_on_entry",
              "sync_checkpoints"
            ]
          }
        ],
        "reasoning": "Merging banking and social via federation strategy.",
        "riskAssessment": {
          "conflicts": 0,
          "resolutionConfidence": 0.9,
          "estimatedComplexity": 5
        }
      },
      "game::social": {
        "mergeStrategy": "federation",
        "agreements": [
          {
            "type": "shared_law",
            "description": "Both universes maintain data integrity",
            "implementation": [
              "validate_on_entry",
              "sync_checkpoints"
            ]
          }
        ],
        "reasoning": "Merging social and game via federation strategy.",
        "riskAssessment": {
          "conflicts": 0,
          "resolutionConfidence": 0.9,
          "estimatedComplexity": 5
        }
      },
      "game::physics": {
        "mergeStrategy": "federation",
        "agreements": [
          {
            "type": "shared_law",
            "description": "Both universes maintain data integrity",
            "implementation": [
              "validate_on_entry",
              "sync_checkpoints"
            ]
          }
        ],
        "reasoning": "Merging game and physics via federation strategy.",
        "riskAssessment": {
          "conflicts": 0,
          "resolutionConfidence": 0.9,
          "estimatedComplexity": 5
        }
      },
      "physics::workflow": {
        "mergeStrategy": "federation",
        "agreements": [
          {
            "type": "shared_law",
            "description": "Both universes maintain data integrity",
            "implementation": [
              "validate_on_entry",
              "sync_checkpoints"
            ]
          }
        ],
        "reasoning": "Merging physics and workflow via federation strategy.",
        "riskAssessment": {
          "conflicts": 0,
          "resolutionConfidence": 0.9,
          "estimatedComplexity": 5
        }
      },
      "banking::workflow": {
        "mergeStrategy": "federation",
        "agreements": [
          {
            "type": "shared_law",
            "description": "Both universes maintain data integrity",
            "implementation": [
              "validate_on_entry",
              "sync_checkpoints"
            ]
          }
        ],
        "reasoning": "Merging workflow and banking via federation strategy.",
        "riskAssessment": {
          "conflicts": 0,
          "resolutionConfidence": 0.9,
          "estimatedComplexity": 5
        }
      }
    },
    "narrator": {
      "kid": {
        "summaryTemplate": "A kid-friendly story of 5 events",
        "keyInsights": [
          "Event chain demonstrates causality",
          "All invariants maintained"
        ],
        "sampleStory": [
          {
            "timestamp": 1759629755119,
            "speaker": "System",
            "text": "Something happened to entity-6! It was a transfer.",
            "context": {
              "value": 17.74940790972117
            },
            "causalLinks": []
          },
          {
            "timestamp": 1759629756119,
            "speaker": "System",
            "text": "Something happened to entity-5! It was a delete.",
            "context": {
              "value": 78.54139643815165
            },
            "causalLinks": [
              "event-0"
            ]
          },
          {
            "timestamp": 1759629757119,
            "speaker": "System",
            "text": "Something happened to entity-9! It was a transfer.",
            "context": {
              "value": 60.20879355133293
            },
            "causalLinks": [
              "event-1"
            ]
          }
        ]
      },
      "pm": {
        "summaryTemplate": "A pm-friendly story of 5 events",
        "keyInsights": [
          "Event chain demonstrates causality",
          "All invariants maintained"
        ],
        "sampleStory": [
          {
            "timestamp": 1759629755120,
            "speaker": "System",
            "text": "User story: As entity-8, the system executed create at 2025-10-05T02:02:35.120Z.",
            "context": {
              "value": 35.80984491088228
            },
            "causalLinks": []
          },
          {
            "timestamp": 1759629756120,
            "speaker": "System",
            "text": "User story: As entity-0, the system executed delete at 2025-10-05T02:02:36.120Z.",
            "context": {
              "value": 73.51859921617012
            },
            "causalLinks": [
              "event-0"
            ]
          },
          {
            "timestamp": 1759629757120,
            "speaker": "System",
            "text": "User story: As entity-7, the system executed create at 2025-10-05T02:02:37.120Z.",
            "context": {
              "value": 24.485451622186226
            },
            "causalLinks": [
              "event-1"
            ]
          }
        ]
      },
      "engineer": {
        "summaryTemplate": "A engineer-friendly story of 5 events",
        "keyInsights": [
          "Event chain demonstrates causality",
          "All invariants maintained"
        ],
        "sampleStory": [
          {
            "timestamp": 1759629755121,
            "speaker": "System",
            "text": "Event event-0: update operation on entity-8 with payload {\"value\":13.853010215941053}",
            "context": {
              "value": 13.853010215941053
            },
            "causalLinks": []
          },
          {
            "timestamp": 1759629756121,
            "speaker": "System",
            "text": "Event event-1: create operation on entity-9 with payload {\"value\":83.79425020772537}",
            "context": {
              "value": 83.79425020772537
            },
            "causalLinks": [
              "event-0"
            ]
          },
          {
            "timestamp": 1759629757121,
            "speaker": "System",
            "text": "Event event-2: create operation on entity-0 with payload {\"value\":72.01730693796398}",
            "context": {
              "value": 72.01730693796398
            },
            "causalLinks": [
              "event-1"
            ]
          }
        ]
      }
    },
    "explorer": {
      "quantum": {
        "paradoxDescription": "Conflicting time-travel law with causality",
        "scenarios": [
          {
            "id": "scenario-0-1",
            "name": "Timeline A: No time travel",
            "initialState": {},
            "interventions": [],
            "expectedOutcomes": [
              "stable"
            ]
          },
          {
            "id": "scenario-0-2",
            "name": "Timeline B: Controlled time travel",
            "initialState": {},
            "interventions": [
              {
                "time": 1000,
                "action": "time_jump",
                "target": "system",
                "params": {
                  "delta": -500
                }
              }
            ],
            "expectedOutcomes": [
              "paradox_resolved",
              "stable"
            ]
          }
        ],
        "recommendations": [
          "Allow controlled time travel with causality locks"
        ]
      },
      "temporal": {
        "paradoxDescription": "Conflicting time-travel law with causality",
        "scenarios": [
          {
            "id": "scenario-2-1",
            "name": "Timeline A: No time travel",
            "initialState": {},
            "interventions": [],
            "expectedOutcomes": [
              "stable"
            ]
          },
          {
            "id": "scenario-2-2",
            "name": "Timeline B: Controlled time travel",
            "initialState": {},
            "interventions": [
              {
                "time": 1000,
                "action": "time_jump",
                "target": "system",
                "params": {
                  "delta": -500
                }
              }
            ],
            "expectedOutcomes": [
              "paradox_resolved",
              "stable"
            ]
          }
        ],
        "recommendations": [
          "Allow controlled time travel with causality locks"
        ]
      },
      "logical": {
        "paradoxDescription": "Conflicting time-travel law with causality",
        "scenarios": [
          {
            "id": "scenario-3-1",
            "name": "Timeline A: No time travel",
            "initialState": {},
            "interventions": [],
            "expectedOutcomes": [
              "stable"
            ]
          },
          {
            "id": "scenario-3-2",
            "name": "Timeline B: Controlled time travel",
            "initialState": {},
            "interventions": [
              {
                "time": 1000,
                "action": "time_jump",
                "target": "system",
                "params": {
                  "delta": -500
                }
              }
            ],
            "expectedOutcomes": [
              "paradox_resolved",
              "stable"
            ]
          }
        ],
        "recommendations": [
          "Allow controlled time travel with causality locks"
        ]
      },
      "causal": {
        "paradoxDescription": "Conflicting time-travel law with causality",
        "scenarios": [
          {
            "id": "scenario-4-1",
            "name": "Timeline A: No time travel",
            "initialState": {},
            "interventions": [],
            "expectedOutcomes": [
              "stable"
            ]
          },
          {
            "id": "scenario-4-2",
            "name": "Timeline B: Controlled time travel",
            "initialState": {},
            "interventions": [
              {
                "time": 1000,
                "action": "time_jump",
                "target": "system",
                "params": {
                  "delta": -500
                }
              }
            ],
            "expectedOutcomes": [
              "paradox_resolved",
              "stable"
            ]
          }
        ],
        "recommendations": [
          "Allow controlled time travel with causality locks"
        ]
      }
    }
  },
  "exemplars": {
    "custodian": [
      {
        "id": "custodian-0",
        "input": {
          "violation": {
            "violationType": "overdraft",
            "entity": "account:72",
            "law": "balance >= 0",
            "snapshot": {
              "balance": -50,
              "transactions": [
                {
                  "amount": -100
                }
              ]
            },
            "timestamp": 1759629750255,
            "severity": "high"
          },
          "laws": [
            "balance >= 0",
            "sum(transactions.amount) === balance",
            "user.verified === true OR transaction.limit < 100"
          ],
          "universeState": {
            "substrate": "banking",
            "entities": {},
            "timestamp": 1759629750255
          }
        },
        "output": {
          "proposal": {
            "id": "proposal-0",
            "type": "rollback",
            "steps": [
              {
                "action": "revert_transaction",
                "target": "account:72",
                "params": {
                  "amount": 100
                },
                "preconditions": [
                  "transaction.exists"
                ],
                "postconditions": [
                  "balance >= 0"
                ]
              }
            ],
            "proof": "Proof: balance >= 0 violated. Rollback restores invariant.",
            "confidence": 0.9448466387270635,
            "estimatedCost": 30
          },
          "reasoning": "Detected overdraft on account:72. Proposing patch to restore law: balance >= 0",
          "alternatives": []
        },
        "metadata": {
          "substrate": "banking",
          "complexity": 10,
          "verificationPassed": true,
          "generatedAt": 1759629750255
        }
      },
      {
        "id": "custodian-80",
        "input": {
          "violation": {
            "violationType": "invalid_transfer",
            "entity": "transaction:8526",
            "law": "sum(transactions.amount) === balance",
            "snapshot": {
              "fromBalance": 50,
              "toBalance": 200,
              "transferAmount": 100
            },
            "timestamp": 1759629750256,
            "severity": "medium"
          },
          "laws": [
            "balance >= 0",
            "sum(transactions.amount) === balance",
            "user.verified === true OR transaction.limit < 100"
          ],
          "universeState": {
            "substrate": "banking",
            "entities": {},
            "timestamp": 1759629750256
          }
        },
        "output": {
          "proposal": {
            "id": "proposal-80",
            "type": "rollback",
            "steps": [
              {
                "action": "revert_transaction",
                "target": "transaction:8526",
                "params": {
                  "amount": 100
                },
                "preconditions": [
                  "transaction.exists"
                ],
                "postconditions": [
                  "balance >= 0"
                ]
              }
            ],
            "proof": "Proof: sum(transactions.amount) === balance violated. Rollback restores invariant.",
            "confidence": 0.8807460407004296,
            "estimatedCost": 1
          },
          "reasoning": "Detected invalid_transfer on transaction:8526. Proposing rollback to restore law: sum(transactions.amount) === balance",
          "alternatives": []
        },
        "metadata": {
          "substrate": "banking",
          "complexity": 8,
          "verificationPassed": true,
          "generatedAt": 1759629750256
        }
      },
      {
        "id": "custodian-160",
        "input": {
          "violation": {
            "violationType": "overdraft",
            "entity": "account:340",
            "law": "balance >= 0",
            "snapshot": {
              "balance": -50,
              "transactions": [
                {
                  "amount": -100
                }
              ]
            },
            "timestamp": 1759629750256,
            "severity": "high"
          },
          "laws": [
            "balance >= 0",
            "sum(transactions.amount) === balance",
            "user.verified === true OR transaction.limit < 100"
          ],
          "universeState": {
            "substrate": "banking",
            "entities": {},
            "timestamp": 1759629750256
          }
        },
        "output": {
          "proposal": {
            "id": "proposal-160",
            "type": "rollback",
            "steps": [
              {
                "action": "revert_transaction",
                "target": "account:340",
                "params": {
                  "amount": 100
                },
                "preconditions": [
                  "transaction.exists"
                ],
                "postconditions": [
                  "balance >= 0"
                ]
              }
            ],
            "proof": "Proof: balance >= 0 violated. Rollback restores invariant.",
            "confidence": 0.9645291123155952,
            "estimatedCost": 6
          },
          "reasoning": "Detected overdraft on account:340. Proposing patch to restore law: balance >= 0",
          "alternatives": []
        },
        "metadata": {
          "substrate": "banking",
          "complexity": 6,
          "verificationPassed": true,
          "generatedAt": 1759629750256
        }
      },
      {
        "id": "custodian-240",
        "input": {
          "violation": {
            "violationType": "invalid_transfer",
            "entity": "transaction:1141",
            "law": "sum(transactions.amount) === balance",
            "snapshot": {
              "fromBalance": 50,
              "toBalance": 200,
              "transferAmount": 100
            },
            "timestamp": 1759629750256,
            "severity": "medium"
          },
          "laws": [
            "balance >= 0",
            "sum(transactions.amount) === balance",
            "user.verified === true OR transaction.limit < 100"
          ],
          "universeState": {
            "substrate": "banking",
            "entities": {},
            "timestamp": 1759629750256
          }
        },
        "output": {
          "proposal": {
            "id": "proposal-240",
            "type": "rollback",
            "steps": [
              {
                "action": "revert_transaction",
                "target": "transaction:1141",
                "params": {
                  "amount": 100
                },
                "preconditions": [
                  "transaction.exists"
                ],
                "postconditions": [
                  "balance >= 0"
                ]
              }
            ],
            "proof": "Proof: sum(transactions.amount) === balance violated. Rollback restores invariant.",
            "confidence": 0.971787065730656,
            "estimatedCost": 72
          },
          "reasoning": "Detected invalid_transfer on transaction:1141. Proposing patch to restore law: sum(transactions.amount) === balance",
          "alternatives": []
        },
        "metadata": {
          "substrate": "banking",
          "complexity": 5,
          "verificationPassed": true,
          "generatedAt": 1759629750256
        }
      },
      {
        "id": "custodian-320",
        "input": {
          "violation": {
            "violationType": "overdraft",
            "entity": "account:522",
            "law": "balance >= 0",
            "snapshot": {
              "balance": -50,
              "transactions": [
                {
                  "amount": -100
                }
              ]
            },
            "timestamp": 1759629750257,
            "severity": "high"
          },
          "laws": [
            "balance >= 0",
            "sum(transactions.amount) === balance",
            "user.verified === true OR transaction.limit < 100"
          ],
          "universeState": {
            "substrate": "banking",
            "entities": {},
            "timestamp": 1759629750257
          }
        },
        "output": {
          "proposal": {
            "id": "proposal-320",
            "type": "patch",
            "steps": [
              {
                "action": "revert_transaction",
                "target": "account:522",
                "params": {
                  "amount": 100
                },
                "preconditions": [
                  "transaction.exists"
                ],
                "postconditions": [
                  "balance >= 0"
                ]
              }
            ],
            "proof": "Proof: balance >= 0 violated. Rollback restores invariant.",
            "confidence": 0.8862520493265122,
            "estimatedCost": 32
          },
          "reasoning": "Detected overdraft on account:522. Proposing patch to restore law: balance >= 0",
          "alternatives": []
        },
        "metadata": {
          "substrate": "banking",
          "complexity": 7,
          "verificationPassed": true,
          "generatedAt": 1759629750257
        }
      }
    ],
    "diplomat": [
      {
        "id": "diplomat-0",
        "input": {
          "universeA": {
            "id": "universe-a-0",
            "laws": [
              "balance >= 0",
              "sum(transactions.amount) === balance",
              "user.verified === true OR transaction.limit < 100"
            ],
            "entities": {},
            "constraints": [
              "law_compliance",
              "data_integrity"
            ],
            "invariants": [
              "monotonic_time",
              "causality"
            ],
            "substrate": "banking"
          },
          "universeB": {
            "id": "universe-b-0",
            "laws": [
              "username.unique === true",
              "connection.mutual === true",
              "post.visibility IN [\"public\", \"friends\", \"private\"]"
            ],
            "entities": {},
            "constraints": [
              "law_compliance",
              "data_integrity"
            ],
            "invariants": [
              "monotonic_time",
              "causality"
            ],
            "substrate": "social"
          },
          "intent": "collaborate"
        },
        "output": {
          "treaty": {
            "id": "treaty-0",
            "universeA": "universe-a-0",
            "universeB": "universe-b-0",
            "agreements": [
              {
                "type": "shared_law",
                "description": "Both universes maintain data integrity",
                "implementation": [
                  "validate_on_entry",
                  "sync_checkpoints"
                ]
              }
            ],
            "conflicts": [],
            "mergeStrategy": "federation",
            "proof": "Treaty preserves invariants in both universes."
          },
          "reasoning": "Merging banking and social via federation strategy.",
          "riskAssessment": {
            "conflicts": 0,
            "resolutionConfidence": 0.9,
            "estimatedComplexity": 5
          }
        },
        "metadata": {
          "substrate": "banking+social",
          "complexity": 4,
          "verificationPassed": true,
          "generatedAt": 1759629752649
        }
      },
      {
        "id": "diplomat-40",
        "input": {
          "universeA": {
            "id": "universe-a-40",
            "laws": [
              "balance >= 0",
              "sum(transactions.amount) === balance",
              "user.verified === true OR transaction.limit < 100"
            ],
            "entities": {},
            "constraints": [
              "law_compliance",
              "data_integrity"
            ],
            "invariants": [
              "monotonic_time",
              "causality"
            ],
            "substrate": "banking"
          },
          "universeB": {
            "id": "universe-b-40",
            "laws": [
              "username.unique === true",
              "connection.mutual === true",
              "post.visibility IN [\"public\", \"friends\", \"private\"]"
            ],
            "entities": {},
            "constraints": [
              "law_compliance",
              "data_integrity"
            ],
            "invariants": [
              "monotonic_time",
              "causality"
            ],
            "substrate": "social"
          },
          "intent": "collaborate"
        },
        "output": {
          "treaty": {
            "id": "treaty-40",
            "universeA": "universe-a-40",
            "universeB": "universe-b-40",
            "agreements": [
              {
                "type": "shared_law",
                "description": "Both universes maintain data integrity",
                "implementation": [
                  "validate_on_entry",
                  "sync_checkpoints"
                ]
              }
            ],
            "conflicts": [],
            "mergeStrategy": "federation",
            "proof": "Treaty preserves invariants in both universes."
          },
          "reasoning": "Merging banking and social via federation strategy.",
          "riskAssessment": {
            "conflicts": 0,
            "resolutionConfidence": 0.9,
            "estimatedComplexity": 5
          }
        },
        "metadata": {
          "substrate": "banking+social",
          "complexity": 8,
          "verificationPassed": true,
          "generatedAt": 1759629752651
        }
      },
      {
        "id": "diplomat-80",
        "input": {
          "universeA": {
            "id": "universe-a-80",
            "laws": [
              "balance >= 0",
              "sum(transactions.amount) === balance",
              "user.verified === true OR transaction.limit < 100"
            ],
            "entities": {},
            "constraints": [
              "law_compliance",
              "data_integrity"
            ],
            "invariants": [
              "monotonic_time",
              "causality"
            ],
            "substrate": "banking"
          },
          "universeB": {
            "id": "universe-b-80",
            "laws": [
              "username.unique === true",
              "connection.mutual === true",
              "post.visibility IN [\"public\", \"friends\", \"private\"]"
            ],
            "entities": {},
            "constraints": [
              "law_compliance",
              "data_integrity"
            ],
            "invariants": [
              "monotonic_time",
              "causality"
            ],
            "substrate": "social"
          },
          "intent": "merge"
        },
        "output": {
          "treaty": {
            "id": "treaty-80",
            "universeA": "universe-a-80",
            "universeB": "universe-b-80",
            "agreements": [
              {
                "type": "shared_law",
                "description": "Both universes maintain data integrity",
                "implementation": [
                  "validate_on_entry",
                  "sync_checkpoints"
                ]
              }
            ],
            "conflicts": [],
            "mergeStrategy": "federation",
            "proof": "Treaty preserves invariants in both universes."
          },
          "reasoning": "Merging banking and social via federation strategy.",
          "riskAssessment": {
            "conflicts": 0,
            "resolutionConfidence": 0.9,
            "estimatedComplexity": 5
          }
        },
        "metadata": {
          "substrate": "banking+social",
          "complexity": 10,
          "verificationPassed": true,
          "generatedAt": 1759629752651
        }
      },
      {
        "id": "diplomat-120",
        "input": {
          "universeA": {
            "id": "universe-a-120",
            "laws": [
              "balance >= 0",
              "sum(transactions.amount) === balance",
              "user.verified === true OR transaction.limit < 100"
            ],
            "entities": {},
            "constraints": [
              "law_compliance",
              "data_integrity"
            ],
            "invariants": [
              "monotonic_time",
              "causality"
            ],
            "substrate": "banking"
          },
          "universeB": {
            "id": "universe-b-120",
            "laws": [
              "username.unique === true",
              "connection.mutual === true",
              "post.visibility IN [\"public\", \"friends\", \"private\"]"
            ],
            "entities": {},
            "constraints": [
              "law_compliance",
              "data_integrity"
            ],
            "invariants": [
              "monotonic_time",
              "causality"
            ],
            "substrate": "social"
          },
          "intent": "merge"
        },
        "output": {
          "treaty": {
            "id": "treaty-120",
            "universeA": "universe-a-120",
            "universeB": "universe-b-120",
            "agreements": [
              {
                "type": "shared_law",
                "description": "Both universes maintain data integrity",
                "implementation": [
                  "validate_on_entry",
                  "sync_checkpoints"
                ]
              }
            ],
            "conflicts": [],
            "mergeStrategy": "federation",
            "proof": "Treaty preserves invariants in both universes."
          },
          "reasoning": "Merging banking and social via federation strategy.",
          "riskAssessment": {
            "conflicts": 0,
            "resolutionConfidence": 0.9,
            "estimatedComplexity": 5
          }
        },
        "metadata": {
          "substrate": "banking+social",
          "complexity": 3,
          "verificationPassed": true,
          "generatedAt": 1759629752651
        }
      },
      {
        "id": "diplomat-160",
        "input": {
          "universeA": {
            "id": "universe-a-160",
            "laws": [
              "balance >= 0",
              "sum(transactions.amount) === balance",
              "user.verified === true OR transaction.limit < 100"
            ],
            "entities": {},
            "constraints": [
              "law_compliance",
              "data_integrity"
            ],
            "invariants": [
              "monotonic_time",
              "causality"
            ],
            "substrate": "banking"
          },
          "universeB": {
            "id": "universe-b-160",
            "laws": [
              "username.unique === true",
              "connection.mutual === true",
              "post.visibility IN [\"public\", \"friends\", \"private\"]"
            ],
            "entities": {},
            "constraints": [
              "law_compliance",
              "data_integrity"
            ],
            "invariants": [
              "monotonic_time",
              "causality"
            ],
            "substrate": "social"
          },
          "intent": "observe"
        },
        "output": {
          "treaty": {
            "id": "treaty-160",
            "universeA": "universe-a-160",
            "universeB": "universe-b-160",
            "agreements": [
              {
                "type": "shared_law",
                "description": "Both universes maintain data integrity",
                "implementation": [
                  "validate_on_entry",
                  "sync_checkpoints"
                ]
              }
            ],
            "conflicts": [],
            "mergeStrategy": "federation",
            "proof": "Treaty preserves invariants in both universes."
          },
          "reasoning": "Merging banking and social via federation strategy.",
          "riskAssessment": {
            "conflicts": 0,
            "resolutionConfidence": 0.9,
            "estimatedComplexity": 5
          }
        },
        "metadata": {
          "substrate": "banking+social",
          "complexity": 10,
          "verificationPassed": true,
          "generatedAt": 1759629752651
        }
      }
    ],
    "narrator": [
      {
        "id": "narrator-0",
        "input": {
          "events": [
            {
              "id": "event-0",
              "type": "transfer",
              "entity": "entity-6",
              "timestamp": 1759629755119,
              "causes": [],
              "effects": [
                "event-1"
              ],
              "data": {
                "value": 17.74940790972117
              }
            },
            {
              "id": "event-1",
              "type": "delete",
              "entity": "entity-5",
              "timestamp": 1759629756119,
              "causes": [
                "event-0"
              ],
              "effects": [
                "event-2"
              ],
              "data": {
                "value": 78.54139643815165
              }
            },
            {
              "id": "event-2",
              "type": "transfer",
              "entity": "entity-9",
              "timestamp": 1759629757119,
              "causes": [
                "event-1"
              ],
              "effects": [
                "event-3"
              ],
              "data": {
                "value": 60.20879355133293
              }
            },
            {
              "id": "event-3",
              "type": "transfer",
              "entity": "entity-4",
              "timestamp": 1759629758119,
              "causes": [
                "event-2"
              ],
              "effects": [
                "event-4"
              ],
              "data": {
                "value": 44.58765714018875
              }
            },
            {
              "id": "event-4",
              "type": "transfer",
              "entity": "entity-1",
              "timestamp": 1759629759119,
              "causes": [
                "event-3"
              ],
              "effects": [],
              "data": {
                "value": 67.36519278410607
              }
            }
          ],
          "mode": "kid",
          "focusEntity": "entity-2"
        },
        "output": {
          "story": [
            {
              "timestamp": 1759629755119,
              "speaker": "System",
              "text": "Something happened to entity-6! It was a transfer.",
              "context": {
                "value": 17.74940790972117
              },
              "causalLinks": []
            },
            {
              "timestamp": 1759629756119,
              "speaker": "System",
              "text": "Something happened to entity-5! It was a delete.",
              "context": {
                "value": 78.54139643815165
              },
              "causalLinks": [
                "event-0"
              ]
            },
            {
              "timestamp": 1759629757119,
              "speaker": "System",
              "text": "Something happened to entity-9! It was a transfer.",
              "context": {
                "value": 60.20879355133293
              },
              "causalLinks": [
                "event-1"
              ]
            },
            {
              "timestamp": 1759629758119,
              "speaker": "System",
              "text": "Something happened to entity-4! It was a transfer.",
              "context": {
                "value": 44.58765714018875
              },
              "causalLinks": [
                "event-2"
              ]
            },
            {
              "timestamp": 1759629759119,
              "speaker": "System",
              "text": "Something happened to entity-1! It was a transfer.",
              "context": {
                "value": 67.36519278410607
              },
              "causalLinks": [
                "event-3"
              ]
            }
          ],
          "summary": "A kid-friendly story of 5 events",
          "keyInsights": [
            "Event chain demonstrates causality",
            "All invariants maintained"
          ],
          "causalChains": [
            {
              "trigger": "event-0",
              "chain": [
                "event-0",
                "event-1",
                "event-2",
                "event-3",
                "event-4"
              ],
              "outcome": "transfer"
            }
          ]
        },
        "metadata": {
          "substrate": "narrative",
          "complexity": 5,
          "verificationPassed": true,
          "generatedAt": 1759629755120
        }
      },
      {
        "id": "narrator-60",
        "input": {
          "events": [
            {
              "id": "event-0",
              "type": "update",
              "entity": "entity-3",
              "timestamp": 1759629755126,
              "causes": [],
              "effects": [
                "event-1"
              ],
              "data": {
                "value": 98.79146751659616
              }
            },
            {
              "id": "event-1",
              "type": "transfer",
              "entity": "entity-9",
              "timestamp": 1759629756126,
              "causes": [
                "event-0"
              ],
              "effects": [
                "event-2"
              ],
              "data": {
                "value": 25.89049838110857
              }
            },
            {
              "id": "event-2",
              "type": "transfer",
              "entity": "entity-8",
              "timestamp": 1759629757126,
              "causes": [
                "event-1"
              ],
              "effects": [
                "event-3"
              ],
              "data": {
                "value": 19.355524911399023
              }
            },
            {
              "id": "event-3",
              "type": "update",
              "entity": "entity-0",
              "timestamp": 1759629758126,
              "causes": [
                "event-2"
              ],
              "effects": [
                "event-4"
              ],
              "data": {
                "value": 7.621698695669754
              }
            },
            {
              "id": "event-4",
              "type": "create",
              "entity": "entity-6",
              "timestamp": 1759629759126,
              "causes": [
                "event-3"
              ],
              "effects": [],
              "data": {
                "value": 8.91265659601661
              }
            }
          ],
          "mode": "kid",
          "focusEntity": "entity-3"
        },
        "output": {
          "story": [
            {
              "timestamp": 1759629755126,
              "speaker": "System",
              "text": "Something happened to entity-3! It was a update.",
              "context": {
                "value": 98.79146751659616
              },
              "causalLinks": []
            },
            {
              "timestamp": 1759629756126,
              "speaker": "System",
              "text": "Something happened to entity-9! It was a transfer.",
              "context": {
                "value": 25.89049838110857
              },
              "causalLinks": [
                "event-0"
              ]
            },
            {
              "timestamp": 1759629757126,
              "speaker": "System",
              "text": "Something happened to entity-8! It was a transfer.",
              "context": {
                "value": 19.355524911399023
              },
              "causalLinks": [
                "event-1"
              ]
            },
            {
              "timestamp": 1759629758126,
              "speaker": "System",
              "text": "Something happened to entity-0! It was a update.",
              "context": {
                "value": 7.621698695669754
              },
              "causalLinks": [
                "event-2"
              ]
            },
            {
              "timestamp": 1759629759126,
              "speaker": "System",
              "text": "Something happened to entity-6! It was a create.",
              "context": {
                "value": 8.91265659601661
              },
              "causalLinks": [
                "event-3"
              ]
            }
          ],
          "summary": "A kid-friendly story of 5 events",
          "keyInsights": [
            "Event chain demonstrates causality",
            "All invariants maintained"
          ],
          "causalChains": [
            {
              "trigger": "event-0",
              "chain": [
                "event-0",
                "event-1",
                "event-2",
                "event-3",
                "event-4"
              ],
              "outcome": "create"
            }
          ]
        },
        "metadata": {
          "substrate": "narrative",
          "complexity": 5,
          "verificationPassed": true,
          "generatedAt": 1759629755126
        }
      },
      {
        "id": "narrator-120",
        "input": {
          "events": [
            {
              "id": "event-0",
              "type": "transfer",
              "entity": "entity-6",
              "timestamp": 1759629755133,
              "causes": [],
              "effects": [
                "event-1"
              ],
              "data": {
                "value": 60.7161272974297
              }
            },
            {
              "id": "event-1",
              "type": "create",
              "entity": "entity-4",
              "timestamp": 1759629756133,
              "causes": [
                "event-0"
              ],
              "effects": [
                "event-2"
              ],
              "data": {
                "value": 66.79175920284221
              }
            },
            {
              "id": "event-2",
              "type": "create",
              "entity": "entity-8",
              "timestamp": 1759629757133,
              "causes": [
                "event-1"
              ],
              "effects": [
                "event-3"
              ],
              "data": {
                "value": 40.050229314506545
              }
            },
            {
              "id": "event-3",
              "type": "create",
              "entity": "entity-2",
              "timestamp": 1759629758133,
              "causes": [
                "event-2"
              ],
              "effects": [
                "event-4"
              ],
              "data": {
                "value": 25.455130455105703
              }
            },
            {
              "id": "event-4",
              "type": "delete",
              "entity": "entity-0",
              "timestamp": 1759629759133,
              "causes": [
                "event-3"
              ],
              "effects": [],
              "data": {
                "value": 96.61460922091727
              }
            }
          ],
          "mode": "kid",
          "focusEntity": "entity-6"
        },
        "output": {
          "story": [
            {
              "timestamp": 1759629755133,
              "speaker": "System",
              "text": "Something happened to entity-6! It was a transfer.",
              "context": {
                "value": 60.7161272974297
              },
              "causalLinks": []
            },
            {
              "timestamp": 1759629756133,
              "speaker": "System",
              "text": "Something happened to entity-4! It was a create.",
              "context": {
                "value": 66.79175920284221
              },
              "causalLinks": [
                "event-0"
              ]
            },
            {
              "timestamp": 1759629757133,
              "speaker": "System",
              "text": "Something happened to entity-8! It was a create.",
              "context": {
                "value": 40.050229314506545
              },
              "causalLinks": [
                "event-1"
              ]
            },
            {
              "timestamp": 1759629758133,
              "speaker": "System",
              "text": "Something happened to entity-2! It was a create.",
              "context": {
                "value": 25.455130455105703
              },
              "causalLinks": [
                "event-2"
              ]
            },
            {
              "timestamp": 1759629759133,
              "speaker": "System",
              "text": "Something happened to entity-0! It was a delete.",
              "context": {
                "value": 96.61460922091727
              },
              "causalLinks": [
                "event-3"
              ]
            }
          ],
          "summary": "A kid-friendly story of 5 events",
          "keyInsights": [
            "Event chain demonstrates causality",
            "All invariants maintained"
          ],
          "causalChains": [
            {
              "trigger": "event-0",
              "chain": [
                "event-0",
                "event-1",
                "event-2",
                "event-3",
                "event-4"
              ],
              "outcome": "delete"
            }
          ]
        },
        "metadata": {
          "substrate": "narrative",
          "complexity": 5,
          "verificationPassed": true,
          "generatedAt": 1759629755133
        }
      },
      {
        "id": "narrator-180",
        "input": {
          "events": [
            {
              "id": "event-0",
              "type": "update",
              "entity": "entity-4",
              "timestamp": 1759629755136,
              "causes": [],
              "effects": [
                "event-1"
              ],
              "data": {
                "value": 63.68736771402765
              }
            },
            {
              "id": "event-1",
              "type": "transfer",
              "entity": "entity-7",
              "timestamp": 1759629756136,
              "causes": [
                "event-0"
              ],
              "effects": [
                "event-2"
              ],
              "data": {
                "value": 19.493714799413286
              }
            },
            {
              "id": "event-2",
              "type": "create",
              "entity": "entity-7",
              "timestamp": 1759629757136,
              "causes": [
                "event-1"
              ],
              "effects": [
                "event-3"
              ],
              "data": {
                "value": 59.925056532003126
              }
            },
            {
              "id": "event-3",
              "type": "transfer",
              "entity": "entity-8",
              "timestamp": 1759629758136,
              "causes": [
                "event-2"
              ],
              "effects": [
                "event-4"
              ],
              "data": {
                "value": 1.4707215112045757
              }
            },
            {
              "id": "event-4",
              "type": "delete",
              "entity": "entity-9",
              "timestamp": 1759629759136,
              "causes": [
                "event-3"
              ],
              "effects": [],
              "data": {
                "value": 20.10219147437575
              }
            }
          ],
          "mode": "kid",
          "focusEntity": "entity-9"
        },
        "output": {
          "story": [
            {
              "timestamp": 1759629755136,
              "speaker": "System",
              "text": "Something happened to entity-4! It was a update.",
              "context": {
                "value": 63.68736771402765
              },
              "causalLinks": []
            },
            {
              "timestamp": 1759629756136,
              "speaker": "System",
              "text": "Something happened to entity-7! It was a transfer.",
              "context": {
                "value": 19.493714799413286
              },
              "causalLinks": [
                "event-0"
              ]
            },
            {
              "timestamp": 1759629757136,
              "speaker": "System",
              "text": "Something happened to entity-7! It was a create.",
              "context": {
                "value": 59.925056532003126
              },
              "causalLinks": [
                "event-1"
              ]
            },
            {
              "timestamp": 1759629758136,
              "speaker": "System",
              "text": "Something happened to entity-8! It was a transfer.",
              "context": {
                "value": 1.4707215112045757
              },
              "causalLinks": [
                "event-2"
              ]
            },
            {
              "timestamp": 1759629759136,
              "speaker": "System",
              "text": "Something happened to entity-9! It was a delete.",
              "context": {
                "value": 20.10219147437575
              },
              "causalLinks": [
                "event-3"
              ]
            }
          ],
          "summary": "A kid-friendly story of 5 events",
          "keyInsights": [
            "Event chain demonstrates causality",
            "All invariants maintained"
          ],
          "causalChains": [
            {
              "trigger": "event-0",
              "chain": [
                "event-0",
                "event-1",
                "event-2",
                "event-3",
                "event-4"
              ],
              "outcome": "delete"
            }
          ]
        },
        "metadata": {
          "substrate": "narrative",
          "complexity": 5,
          "verificationPassed": true,
          "generatedAt": 1759629755136
        }
      },
      {
        "id": "narrator-240",
        "input": {
          "events": [
            {
              "id": "event-0",
              "type": "delete",
              "entity": "entity-7",
              "timestamp": 1759629755144,
              "causes": [],
              "effects": [
                "event-1"
              ],
              "data": {
                "value": 26.54352445054562
              }
            },
            {
              "id": "event-1",
              "type": "update",
              "entity": "entity-7",
              "timestamp": 1759629756144,
              "causes": [
                "event-0"
              ],
              "effects": [
                "event-2"
              ],
              "data": {
                "value": 91.04065095874189
              }
            },
            {
              "id": "event-2",
              "type": "update",
              "entity": "entity-5",
              "timestamp": 1759629757144,
              "causes": [
                "event-1"
              ],
              "effects": [
                "event-3"
              ],
              "data": {
                "value": 71.61447130162185
              }
            },
            {
              "id": "event-3",
              "type": "transfer",
              "entity": "entity-0",
              "timestamp": 1759629758144,
              "causes": [
                "event-2"
              ],
              "effects": [
                "event-4"
              ],
              "data": {
                "value": 2.6953680229327093
              }
            },
            {
              "id": "event-4",
              "type": "update",
              "entity": "entity-1",
              "timestamp": 1759629759144,
              "causes": [
                "event-3"
              ],
              "effects": [],
              "data": {
                "value": 0.3305919714837957
              }
            }
          ],
          "mode": "kid",
          "focusEntity": "entity-3"
        },
        "output": {
          "story": [
            {
              "timestamp": 1759629755144,
              "speaker": "System",
              "text": "Something happened to entity-7! It was a delete.",
              "context": {
                "value": 26.54352445054562
              },
              "causalLinks": []
            },
            {
              "timestamp": 1759629756144,
              "speaker": "System",
              "text": "Something happened to entity-7! It was a update.",
              "context": {
                "value": 91.04065095874189
              },
              "causalLinks": [
                "event-0"
              ]
            },
            {
              "timestamp": 1759629757144,
              "speaker": "System",
              "text": "Something happened to entity-5! It was a update.",
              "context": {
                "value": 71.61447130162185
              },
              "causalLinks": [
                "event-1"
              ]
            },
            {
              "timestamp": 1759629758144,
              "speaker": "System",
              "text": "Something happened to entity-0! It was a transfer.",
              "context": {
                "value": 2.6953680229327093
              },
              "causalLinks": [
                "event-2"
              ]
            },
            {
              "timestamp": 1759629759144,
              "speaker": "System",
              "text": "Something happened to entity-1! It was a update.",
              "context": {
                "value": 0.3305919714837957
              },
              "causalLinks": [
                "event-3"
              ]
            }
          ],
          "summary": "A kid-friendly story of 5 events",
          "keyInsights": [
            "Event chain demonstrates causality",
            "All invariants maintained"
          ],
          "causalChains": [
            {
              "trigger": "event-0",
              "chain": [
                "event-0",
                "event-1",
                "event-2",
                "event-3",
                "event-4"
              ],
              "outcome": "update"
            }
          ]
        },
        "metadata": {
          "substrate": "narrative",
          "complexity": 5,
          "verificationPassed": true,
          "generatedAt": 1759629755144
        }
      }
    ],
    "explorer": [
      {
        "id": "explorer-0",
        "input": {
          "paradox": {
            "id": "paradox-0",
            "type": "quantum",
            "description": "Conflicting time-travel law with causality",
            "conflictingLaws": [
              "time.forward_only",
              "time_travel.allowed"
            ],
            "affectedEntities": [
              "entity-1"
            ]
          },
          "universeState": {},
          "explorationDepth": 3
        },
        "output": {
          "scenarios": [
            {
              "id": "scenario-0-1",
              "name": "Timeline A: No time travel",
              "initialState": {},
              "interventions": [],
              "expectedOutcomes": [
                "stable"
              ]
            },
            {
              "id": "scenario-0-2",
              "name": "Timeline B: Controlled time travel",
              "initialState": {},
              "interventions": [
                {
                  "time": 1000,
                  "action": "time_jump",
                  "target": "system",
                  "params": {
                    "delta": -500
                  }
                }
              ],
              "expectedOutcomes": [
                "paradox_resolved",
                "stable"
              ]
            }
          ],
          "analysis": {
            "stableOutcomes": 2,
            "paradoxResolutions": 1,
            "emergentBehaviors": [
              "timeline_branching"
            ]
          },
          "recommendations": [
            "Allow controlled time travel with causality locks"
          ]
        },
        "metadata": {
          "substrate": "paradox",
          "complexity": 6,
          "verificationPassed": true,
          "generatedAt": 1759629757743
        }
      },
      {
        "id": "explorer-30",
        "input": {
          "paradox": {
            "id": "paradox-30",
            "type": "quantum",
            "description": "Conflicting time-travel law with causality",
            "conflictingLaws": [
              "time.forward_only",
              "time_travel.allowed"
            ],
            "affectedEntities": [
              "entity-13"
            ]
          },
          "universeState": {},
          "explorationDepth": 3
        },
        "output": {
          "scenarios": [
            {
              "id": "scenario-30-1",
              "name": "Timeline A: No time travel",
              "initialState": {},
              "interventions": [],
              "expectedOutcomes": [
                "stable"
              ]
            },
            {
              "id": "scenario-30-2",
              "name": "Timeline B: Controlled time travel",
              "initialState": {},
              "interventions": [
                {
                  "time": 1000,
                  "action": "time_jump",
                  "target": "system",
                  "params": {
                    "delta": -500
                  }
                }
              ],
              "expectedOutcomes": [
                "paradox_resolved",
                "stable"
              ]
            }
          ],
          "analysis": {
            "stableOutcomes": 2,
            "paradoxResolutions": 1,
            "emergentBehaviors": [
              "timeline_branching"
            ]
          },
          "recommendations": [
            "Allow controlled time travel with causality locks"
          ]
        },
        "metadata": {
          "substrate": "paradox",
          "complexity": 9,
          "verificationPassed": true,
          "generatedAt": 1759629757744
        }
      },
      {
        "id": "explorer-60",
        "input": {
          "paradox": {
            "id": "paradox-60",
            "type": "quantum",
            "description": "Conflicting time-travel law with causality",
            "conflictingLaws": [
              "time.forward_only",
              "time_travel.allowed"
            ],
            "affectedEntities": [
              "entity-9"
            ]
          },
          "universeState": {},
          "explorationDepth": 3
        },
        "output": {
          "scenarios": [
            {
              "id": "scenario-60-1",
              "name": "Timeline A: No time travel",
              "initialState": {},
              "interventions": [],
              "expectedOutcomes": [
                "stable"
              ]
            },
            {
              "id": "scenario-60-2",
              "name": "Timeline B: Controlled time travel",
              "initialState": {},
              "interventions": [
                {
                  "time": 1000,
                  "action": "time_jump",
                  "target": "system",
                  "params": {
                    "delta": -500
                  }
                }
              ],
              "expectedOutcomes": [
                "paradox_resolved",
                "stable"
              ]
            }
          ],
          "analysis": {
            "stableOutcomes": 2,
            "paradoxResolutions": 1,
            "emergentBehaviors": [
              "timeline_branching"
            ]
          },
          "recommendations": [
            "Allow controlled time travel with causality locks"
          ]
        },
        "metadata": {
          "substrate": "paradox",
          "complexity": 5,
          "verificationPassed": true,
          "generatedAt": 1759629757744
        }
      },
      {
        "id": "explorer-90",
        "input": {
          "paradox": {
            "id": "paradox-90",
            "type": "quantum",
            "description": "Conflicting time-travel law with causality",
            "conflictingLaws": [
              "time.forward_only",
              "time_travel.allowed"
            ],
            "affectedEntities": [
              "entity-96"
            ]
          },
          "universeState": {},
          "explorationDepth": 3
        },
        "output": {
          "scenarios": [
            {
              "id": "scenario-90-1",
              "name": "Timeline A: No time travel",
              "initialState": {},
              "interventions": [],
              "expectedOutcomes": [
                "stable"
              ]
            },
            {
              "id": "scenario-90-2",
              "name": "Timeline B: Controlled time travel",
              "initialState": {},
              "interventions": [
                {
                  "time": 1000,
                  "action": "time_jump",
                  "target": "system",
                  "params": {
                    "delta": -500
                  }
                }
              ],
              "expectedOutcomes": [
                "paradox_resolved",
                "stable"
              ]
            }
          ],
          "analysis": {
            "stableOutcomes": 2,
            "paradoxResolutions": 1,
            "emergentBehaviors": [
              "timeline_branching"
            ]
          },
          "recommendations": [
            "Allow controlled time travel with causality locks"
          ]
        },
        "metadata": {
          "substrate": "paradox",
          "complexity": 3,
          "verificationPassed": true,
          "generatedAt": 1759629757744
        }
      },
      {
        "id": "explorer-120",
        "input": {
          "paradox": {
            "id": "paradox-120",
            "type": "quantum",
            "description": "Conflicting time-travel law with causality",
            "conflictingLaws": [
              "time.forward_only",
              "time_travel.allowed"
            ],
            "affectedEntities": [
              "entity-27"
            ]
          },
          "universeState": {},
          "explorationDepth": 3
        },
        "output": {
          "scenarios": [
            {
              "id": "scenario-120-1",
              "name": "Timeline A: No time travel",
              "initialState": {},
              "interventions": [],
              "expectedOutcomes": [
                "stable"
              ]
            },
            {
              "id": "scenario-120-2",
              "name": "Timeline B: Controlled time travel",
              "initialState": {},
              "interventions": [
                {
                  "time": 1000,
                  "action": "time_jump",
                  "target": "system",
                  "params": {
                    "delta": -500
                  }
                }
              ],
              "expectedOutcomes": [
                "paradox_resolved",
                "stable"
              ]
            }
          ],
          "analysis": {
            "stableOutcomes": 2,
            "paradoxResolutions": 1,
            "emergentBehaviors": [
              "timeline_branching"
            ]
          },
          "recommendations": [
            "Allow controlled time travel with causality locks"
          ]
        },
        "metadata": {
          "substrate": "paradox",
          "complexity": 9,
          "verificationPassed": true,
          "generatedAt": 1759629757744
        }
      }
    ]
  }
} as const

export type TrainedAgents = typeof trainedAgents
