name: Examples Smoke Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  smoke-examples:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install
        run: npm ci
      - name: Build
        run: npm run build --if-present
      - name: Run React example smoke
        run: npm run smoke:example:react
      - name: Run Vue example smoke
        run: npm run smoke:example:vue
